[package]
name = "bevy-test"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#Enable small amount of optimisation in debug mode
[profile.dev]
opt-level = 1

# Enable high optimisation for dependencies (incl. Bevy)
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version ="^0.12", features = ["dynamic_linking"]}
noise = "0.8.2"

