[package]
name = "level_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }

serde_json = { workspace = true }
serde = { workspace = true }
